In [4]:
import pandas as pd

In [5]:
import numpy as np

In [ ]:
import openpyxl #ohne diese Bib hätte excel file nicht funktioniert

In [16]:
import os
from sklearn.model_selection import train_test_split

In [1]:
file_path = os.path.join("..","..","..","data","Census-Datensatz.csv")  # Warum 3 Verzeichnisse nach oben? Was heißt join?

NameError: name 'os' is not defined

In [3]:
file_path = os.path.join("..","..","..","data","datensatz.csv")

datensatz = pd.read_csv(file_path)

NameError: name 'pd' is not defined

In [6]:
file_path = os.path.join("..", "..", "..", "data", "datensatz.csv")

datensatz = pd.read_csv(file_path)

FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\..\\data\\datensatz.csv'

In [9]:
file_path = os.path.join("datensatz.csv")

datensatz = pd.read_csv(file_path)
datensatz

      age;workclass;fnlwgt;education;education-num;marital-status;occupation;relationship;race;sex;capital-gain;capital-loss;hours-per-week;native-country;income
0      39; State-gov;77516; Bachelors;13; Never-marri...
1      50; Self-emp-not-inc;83311; Bachelors;13; Marr...
2      38; Private;215646; HS-grad;9; Divorced; Handl...
3      53; Private;234721; 11th;7; Married-civ-spouse...
4      28; Private;338409; Bachelors;13; Married-civ-...
...                                                  ...
32556  27; Private;257302; Assoc-acdm;12; Married-civ...
32557  40; Private;154374; HS-grad;9; Married-civ-spo...
32558  58; Private;151910; HS-grad;9; Widowed; Adm-cl...
32559  22; Private;201490; HS-grad;9; Never-married; ...
32560  52; Self-emp-inc;287927; HS-grad;9; Married-ci...

[32561 rows x 1 columns]

In [10]:
datensatz.describe()

       age;workclass;fnlwgt;education;education-num;marital-status;occupation;relationship;race;sex;capital-gain;capital-loss;hours-per-week;native-country;income
count                                               32561
unique                                              32537
top     25; Private;195994; 1st-4th;2; Never-married; ...
freq                                                    3

In [11]:
file_path = os.path.join("Census-Datensatz.xlsx")

datensatz = pd.read_csv(file_path)
datensatz

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

In [13]:
file_path = os.path.join("Census-Datensatz.xlsx")

datensatz = pd.read_excel(file_path)
datensatz

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [22]:
datensatz.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [18]:
train, test = train_test_split(datensatz, test_size=0.3)
train

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
23502,31,?,213771,HS-grad,9,Widowed,?,Unmarried,White,Female,0,0,36,United-States,<=50K
30259,39,Federal-gov,363630,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,Black,Male,7688,0,52,United-States,>50K
19709,58,Self-emp-not-inc,147653,10th,6,Married-civ-spouse,Craft-repair,Wife,White,Female,0,1977,35,?,>50K
9074,54,Private,39493,Assoc-voc,11,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,20,United-States,<=50K
32141,34,Private,193344,Some-college,10,Never-married,Adm-clerical,Unmarried,White,Female,0,0,40,Germany,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16588,70,Self-emp-not-inc,36311,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,35,United-States,>50K
6496,20,Private,260199,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Female,0,0,10,United-States,<=50K
14620,56,Self-emp-not-inc,84774,Assoc-acdm,12,Married-civ-spouse,Farming-fishing,Wife,White,Female,0,0,40,United-States,<=50K
24829,21,Private,177526,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,40,United-States,<=50K
1628,45,Private,428350,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,1740,40,United-States,<=50K

In [19]:
train.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,22792.000000,2.279200e+04,22792.000000,22792.000000,22792.000000,22792.000000
mean,38.527773,1.898792e+05,10.067919,1022.535012,88.128027,40.402378
std,13.651071,1.061297e+05,2.575752,7038.297374,404.791846,12.346405
min,17.000000,1.376900e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.177890e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781745e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.375492e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [20]:
test.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,9769.000000,9.769000e+03,9769.000000,9769.000000,9769.000000,9769.000000
mean,38.707340,1.895430e+05,10.110451,1206.234620,85.380899,40.519296
std,13.615449,1.041900e+05,2.565518,8136.467822,398.668110,12.350061
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.179630e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.790130e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.364970e+05,13.000000,0.000000,0.000000,45.000000
max,90.000000,1.268339e+06,16.000000,99999.000000,4356.000000,99.000000

In [23]:
datensatz[:1000]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,56,Private,112840,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,55,United-States,>50K
996,45,Private,89325,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,45,United-States,<=50K
997,48,Federal-gov,33109,Bachelors,13,Divorced,Exec-managerial,Unmarried,White,Male,0,0,58,United-States,>50K
998,40,Private,82465,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,2580,0,40,United-States,<=50K
999,39,Self-emp-inc,329980,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,15024,0,50,United-States,>50K

In [24]:
train, test = train_test_split(datensatz[:1000], test_size=0.3)
test

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
901,51,Self-emp-not-inc,175897,9th,5,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,20,United-States,<=50K
850,61,Private,99784,Masters,14,Widowed,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,>50K
555,69,Private,136218,11th,7,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
779,54,Private,279129,Some-college,10,Never-married,Tech-support,Not-in-family,White,Male,0,0,40,United-States,<=50K
372,40,State-gov,184018,Assoc-voc,11,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,38,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,32,Private,364657,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,<=50K
41,53,Self-emp-not-inc,88506,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
726,44,Private,111502,HS-grad,9,Married-civ-spouse,Sales,Wife,White,Female,0,0,40,United-States,<=50K
444,27,Private,405855,9th,5,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,<=50K
490,40,Private,347934,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,35,United-States,<=50K

In [28]:
train, test = train_test_split(datensatz[:100], test_size=0.3)
train

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
55,43,Private,237993,Some-college,10,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
74,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,20,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
72,29,Self-emp-not-inc,162298,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,70,United-States,>50K
46,53,Private,144361,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,38,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
35,48,Private,242406,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,Puerto-Rico,<=50K

In [26]:
train.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,700.000000,7.000000e+02,700.000000,700.000000,700.000000,700.000000
mean,38.175714,1.913652e+05,10.045714,645.224286,100.548571,39.988571
std,13.445241,1.079018e+05,2.622271,2847.543835,427.682415,11.933765
min,17.000000,2.117400e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.161590e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.811430e+05,10.000000,0.000000,0.000000,40.000000
75%,46.000000,2.473005e+05,13.000000,0.000000,0.000000,45.000000
max,90.000000,1.033222e+06,16.000000,34095.000000,2415.000000,99.000000

In [ ]:
test.describe() #woher weiß es, aus dieser Zeile, dass ich jetzt den verkleinerten Datensatz meine? Weil er später im Dokument steht?

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,300.000000,300.000000,300.000000,300.00000,300.000000,300.000000
mean,37.760000,193164.416667,10.173333,456.23000,75.253333,39.613333
std,13.140954,108816.200890,2.369671,1981.97176,374.561249,12.228749
min,17.000000,21906.000000,1.000000,0.00000,0.000000,6.000000
25%,27.000000,114464.250000,9.000000,0.00000,0.000000,35.750000
50%,36.000000,177662.000000,10.000000,0.00000,0.000000,40.000000
75%,47.000000,246326.500000,12.000000,0.00000,0.000000,45.000000
max,76.000000,680390.000000,16.000000,15024.00000,2415.000000,80.000000